// <auto-generated />
using System;
using CourtifyBE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CourtifyBE.Migrations
{
    [DbContext(typeof(CourtifyDbContext))]
    [Migration("20260820030612_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CourtifyBE.Models.Admin", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NAME");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("USERNAME");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("CourtifyBE.Models.BookingAddOns", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BookingId")
                        .HasColumnType("bigint")
                        .HasColumnName("BOOKING_ID");

                    b.Property<long>("EquipmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("EQUIPMENT_ID");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("QUANTITY");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("SUB_TOTAL");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("UNIT_PRICE");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("BookingAddOns");
                });

            modelBuilder.Entity("CourtifyBE.Models.Bookings", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AdminId")
                        .HasColumnType("bigint")
                        .HasColumnName("ADMIN_ID");

                    b.Property<decimal>("BaseAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("BASE_AMOUNT");

                    b.Property<string>("BookingCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("BOOKING_CODE");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("BOOKING_DATE");

                    b.Property<long>("CourtsId")
                        .HasColumnType("bigint")
                        .HasColumnName("COURTS_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CUSTOMER_NAME");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("END_TIME");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("START_TIME");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("STATUS");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("TOTAL_AMOUNT");

                    b.Property<int>("TotalHours")
                        .HasColumnType("integer")
                        .HasColumnName("TOTAL_HOURS");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("CourtsId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("CourtifyBE.Models.CourtCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CATEGORY");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("DESCRIPTION");

                    b.HasKey("Id");

                    b.ToTable("CourtCategories");
                });

            modelBuilder.Entity("CourtifyBE.Models.Courts", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CourtCategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("COURT_CATEGORY_ID");

                    b.Property<string>("CourtName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("COURT_NAME");

                    b.Property<decimal>("HolyRate")
                        .HasColumnType("numeric")
                        .HasColumnName("HOURLY_RATE");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("IS_AVAILABLE");

                    b.Property<long>("VenueId")
                        .HasColumnType("bigint")
                        .HasColumnName("VENUE_ID");

                    b.HasKey("Id");

                    b.HasIndex("CourtCategoryId");

                    b.HasIndex("VenueId");

                    b.ToTable("Courts");
                });

            modelBuilder.Entity("CourtifyBE.Models.EquipmentAddOns", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ITEM_NAME");

                    b.Property<decimal>("RentalFee")
                        .HasColumnType("numeric")
                        .HasColumnName("RENTAL_FEE");

                    b.Property<int>("Stock")
                        .HasColumnType("integer")
                        .HasColumnName("STOCK");

                    b.HasKey("Id");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("CourtifyBE.Models.PaymentReceipt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BookingId")
                        .HasColumnType("bigint")
                        .HasColumnName("BOOKING_ID");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("PAYMENT_METHOD");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("RECEIPT_NUMBER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("PaymentReceipts");
                });

            modelBuilder.Entity("CourtifyBE.Models.Venues", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("ADDRESS");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("NameVenue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NAME_VENUE");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("PHONE_NUMBER");

                    b.HasKey("Id");

                    b.ToTable("Venues");
                });

            modelBuilder.Entity("CourtifyBE.Models.BookingAddOns", b =>
                {
                    b.HasOne("CourtifyBE.Models.Bookings", "Bookings")
                        .WithMany("BookingAddOns")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourtifyBE.Models.EquipmentAddOns", "Equipment")
                        .WithMany("BookingAddOns")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bookings");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("CourtifyBE.Models.Bookings", b =>
                {
                    b.HasOne("CourtifyBE.Models.Admin", "Admin")
                        .WithMany("Bookings")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourtifyBE.Models.Courts", "Courts")
                        .WithMany("Bookings")
                        .HasForeignKey("CourtsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Courts");
                });

            modelBuilder.Entity("CourtifyBE.Models.Courts", b =>
                {
                    b.HasOne("CourtifyBE.Models.CourtCategory", "CourtCategory")
                        .WithMany("Courts")
                        .HasForeignKey("CourtCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourtifyBE.Models.Venues", "Venues")
                        .WithMany("Courts")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourtCategory");

                    b.Navigation("Venues");
                });

            modelBuilder.Entity("CourtifyBE.Models.PaymentReceipt", b =>
                {
                    b.HasOne("CourtifyBE.Models.Bookings", "Bookings")
                        .WithMany("PaymentReceipts")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("CourtifyBE.Models.Admin", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("CourtifyBE.Models.Bookings", b =>
                {
                    b.Navigation("BookingAddOns");

                    b.Navigation("PaymentReceipts");
                });

            modelBuilder.Entity("CourtifyBE.Models.CourtCategory", b =>
                {
                    b.Navigation("Courts");
                });

            modelBuilder.Entity("CourtifyBE.Models.Courts", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("CourtifyBE.Models.EquipmentAddOns", b =>
                {
                    b.Navigation("BookingAddOns");
                });

            modelBuilder.Entity("CourtifyBE.Models.Venues", b =>
                {
                    b.Navigation("Courts");
                });
#pragma warning restore 612, 618
        }
    }
}
